[[redirects]]
  from = "/resume.pdf"
  to = "/Resume - Luke Karrys.pdf"

[[redirects]]
  from = "/index.pdf"
  to = "/Resume - Luke Karrys.pdf"

[[redirects]]
  from = "/pdf"
  to = "/Resume - Luke Karrys.pdf"